### ISSUE TITLE
Remove nullish-coalescing-operator and optional-chaining plugins once preset-env is updated

### ISSUE THREAD

**Issue by satazor** [moxystudio/babel-preset#48]
Null coalescing and optional chaining are now part of ES2020.

The next version of `@babel/preset-env` will have built-in support to transpile these new operators. See: https://github.com/babel/babel/commit/80aa7dc3c6972c0b107dd8b4ed88663141cf8583

Remove `@babel/plugin-proposal-optional-chaining` and `@babel/plugin-proposal-nullish-coalescing-operator` once the new `@babel/preset-env` version is released.

**Comment by acostalima** [comment]
Alright, agreed! 👌
